train: True
eval val: True
eval test: False
print every: 100
plot every: 1000
print sample every: 250
max length: 50
sample every: 20
batch size: 25
epochs: 50
encoder embed: 300
decoder embed: 300
dropout: 0.5
learning rate: 0.01

