train: True
eval val: True
eval test: False
print every: 2500
plot every: 1000
print sample every: 5000
max length: 50
batch size: 50
epochs: 50
encoder embed: 300
decoder embed: 300
dropout: 0.5
learning rate: 0.01
save name: model.test.german.pkl
save model: True
load model: False
