train model: True
eval val: False
eval test: False
print every: 100
plot every: 1000
print sample every: 100
max length: 50
num layers: 2
batch size: 1
epochs: 50
encoder embed: 300
decoder embed: 300
dropout: 0.0
learning rate: 1.0
save name: model.test.german.pkl
save model: False
load model: False
train: data/testing/train.txt
valid: data/testing/valid.txt
test: data/testing/test.txt
#train: data/german/german-task1-train
#valid: data/german/german-task1-dev
#test: data/german/german-task1-test
