train model: True
eval val: True
checkpoint_every: 5000
print every: 100
plot every: 100
print sample every: 100
expt_dir: spanish-balanced-gen1
max_length: 50
num layers: 2
batch size: 20
epochs: 20
encoder embed: 300
decoder embed: 300
dropout: 0.3
# load_model: 2018_11_06_21_33_33/
# load_model: 2018_11_16_09_37_40/
#load_model: decent/
load_model: None
train_path: data/spanish-balanced/train/data.txt
valid_path: data/spanish-balanced/dev/data.txt
# test_path: data/spanish-sigstyle/test/data.txt
# valid_path: data/spanish-sigstyle/test/data.txt
output: spanish-balanced-gen1/spanish-balanced-dev-gen-1.tsv
use_vecs: False
# vecs: ruscorpora.model.bin
vecs: nope
interact: False
