train model: True
eval val: True
eval test: False
print every: 500
plot every: 1000
print sample every: 500
max length: 50
batch size: 10
epochs: 50
encoder embed: 600
decoder embed: 600
dropout: 0.3
learning rate: 0.01
save name: model.test.german.pkl
save model: False
load model: False
train: data/german/german-task1-train
valid: data/german/german-task1-dev
test: data/german/german-task1-test
# train: data/testing/train.txt
# valid: data/testing/valid.txt
# test: data/testing/test.txt
