train model: False
eval val: False
checkpoint_every: 5000
print every: 100
plot every: 100
print sample every: 100
#expt_dir: spanish-balanced-gen1
expt_dir: experiment
max_length: 50
num layers: 2
batch size: 20
epochs: 20
encoder embed: 300
decoder embed: 300
dropout: 0.3
load_model: 2019_01_17_16_31_24/
# load_model: 2018_11_06_21_33_33/
# load_model: 2018_11_16_09_37_40/
# non vec russian model
#load_model: 2018_11_27_17_18_32/
# vec russian model
#load_model: 2018_11_28_19_02_18/
#load_model: decent/
# load_model: None
train_path: data/german/train/data.txt
#valid_path: data/russian/dev/UDdev.txt
valid_path: data/german/dev/data.txt
# test_path: data/spanish-sigstyle/test/data.txt
# valid_path: data/spanish-sigstyle/test/data.txt
output: testing.tsv
use_vecs: False
#vecs: ruscorpora.model.bin
vecs: nope
interact: True
