train model: True
eval val: True
checkpoint_every: 5000
print every: 100
plot every: 100
print sample every: 100
expt_dir: aab-testing
#expt_dir: topk-testing
max_length: 50
num layers: 2
#batch size: 20
batch size: 1
epochs: 3
encoder embed: 300
decoder embed: 300
dropout: 0.3
#load_model: 2019_08_19_03_32_51/
load_model: None
train_path: data/artif-final/aab/train/data.txt
valid_path: data/artif-final/aab/dev/data.txt
#test_path: data/german-balanced/dev/data.txt
# test_path: data/spanish-sigstyle/test/data.txt
# valid_path: data/spanish-sigstyle/test/data.txt
output: aab-testing.tsv
use_vecs: False
# vecs: russian-300-train.stemmed.bin
# vecs: nope
interact: False
